baseURL: '/'
languageCode: ja
defaultContentLanguage: ja
publishDir: public
contentDir: content
title: OTTANJP
theme: ottan
hasCJKLanguage: true
summaryLength: 150
canonifyURLs: true
disqusShortname: ottanjp
paginate: 20
googleAnalytics: UA-54519352-3
rssLimit: 15
permalinks:
  posts: /posts/:year/:month/:slug
markup:
  highlight:
    style: github
params:
  author: ottanxyz
  favicon: images/favicon.ico
  twitter: 'https://twitter.com/ottanxyz/'
  facebook: 'https://www.facebook.com/ottanxyz/'
  github: 'https://github.com/ottanjp/'
  rss: 'https://ottan.jp/index.xml'
  description: Not Defined.
  locale: ja_JP
  fbappId: '808819212572711'
outputs:
  home: [HTML, JSON, RSS]
